#define STAT_PAGE "Stats"
#define STAT_CATEGORY1 "STATS"
#define STAT_CATEGORY2 "CONDITION"
#define STAT_CATEGORY3 "S.P.E.C.I.A.L."
#define STAT_CATEGORY4 "HEALTH"
#define STAT_CATEGORY5 "SOMETHING ELSE"
#define STAT_CATEGORIES { STAT_CATEGORY1, STAT_CATEGORY2, STAT_CATEGORY3, STAT_CATEGORY4, STAT_CATEGORY5 }

#define INVENTORY_PAGE "Inventory"
#define INVENTORY_CATEGORY1 "WEAPONS"
#define INVENTORY_CATEGORY2 "APPAREL"
#define INVENTORY_CATEGORY3 "AID"
#define INVENTORY_CATEGORY4 "AMMO"
#define INVENTORY_CATEGORY5 "MISC"
#define INVENTORY_CATEGORIES { INVENTORY_CATEGORY1, INVENTORY_CATEGORY2, INVENTORY_CATEGORY3, INVENTORY_CATEGORY4, INVENTORY_CATEGORY5 }

#define DATA_PAGE "Data"
#define DATA_CATEGORY1 "WORLD MAP"
#define DATA_CATEGORY2 "LOCAL MAP"
#define DATA_CATEGORY3 "QUESTS"
#define DATA_CATEGORY4 "NOTES"
#define DATA_CATEGORY5 "RADIO"
#define DATA_CATEGORIES { DATA_CATEGORY1, DATA_CATEGORY2, DATA_CATEGORY3, DATA_CATEGORY4, DATA_CATEGORY5 }